package com.learning.ai.helper;

import java.util.Arrays;
import java.util.List;

public class DataHelper {

    public static List<String> getJavaConcepts(){
        return Arrays.asList(
                "Java is a high level, object oriented programming language",
                "Java follows the write once run anywhere principle",
                "JVM executes Java bytecode on different platforms",
                "JRE provides runtime environment for Java applications",
                "JDK contains tools required for Java development",
                "Class is a blueprint for creating objects in Java",
                "Object is an instance of a Java class",
                "Encapsulation hides internal state using private fields",
                "Abstraction exposes only essential behavior to users",
                "Inheritance allows a class to acquire properties of another class",
                "Polymorphism allows methods to behave differently based on object type",
                "Method overloading supports compile time polymorphism",
                "Method overriding supports runtime polymorphism",
                "Interface defines a contract that classes must implement",
                "Abstract class can contain both abstract and concrete methods",
                "Java supports multiple inheritance using interfaces",
                "final keyword prevents modification of variables methods or classes",
                "static keyword belongs to the class rather than instance",
                "this keyword refers to the current object",
                "super keyword refers to parent class object",
                "Constructor initializes objects during creation",
                "Default constructor is provided by compiler if none is defined",
                "Parameterized constructor accepts arguments",
                "Garbage collection automatically frees unused memory",
                "Heap memory stores objects and instance variables",
                "Stack memory stores method calls and local variables",
                "String is immutable in Java",
                "StringBuilder is mutable and not thread safe",
                "StringBuffer is mutable and thread safe",
                "equals method compares object content",
                "hashCode method returns hash value of object",
                "HashMap stores key value pairs without order",
                "LinkedHashMap maintains insertion order",
                "TreeMap stores keys in sorted order",
                "HashSet stores unique elements without order",
                "LinkedHashSet maintains insertion order of elements",
                "TreeSet stores elements in sorted order",
                "ArrayList is a resizable array implementation",
                "LinkedList uses doubly linked list structure",
                "Vector is synchronized version of ArrayList",
                "Iterator allows forward traversal of collection",
                "ListIterator allows bidirectional traversal",
                "Comparable defines natural ordering of objects",
                "Comparator defines custom ordering logic",
                "Exception represents runtime error conditions",
                "Checked exceptions are verified at compile time",
                "Unchecked exceptions occur at runtime",
                "try catch block handles exceptions",
                "finally block executes regardless of exception",
                "throw keyword explicitly throws an exception",
                "throws keyword declares exception propagation",
                "Custom exceptions can be created by extending Exception",
                "Multithreading allows concurrent execution of tasks",
                "Thread class is used to create a new thread",
                "Runnable interface represents a task to be executed",
                "ExecutorService manages thread pools",
                "Synchronization prevents race conditions",
                "synchronized keyword ensures thread safety",
                "volatile keyword ensures visibility of changes",
                "Deadlock occurs when threads wait indefinitely",
                "Callable interface returns a result from thread",
                "Future represents result of asynchronous computation",
                "Java supports functional programming via lambdas",
                "Lambda expression provides concise function syntax",
                "Functional interface has exactly one abstract method",
                "Predicate represents boolean valued function",
                "Consumer accepts input but returns no result",
                "Supplier returns a value without input",
                "Stream API processes collections declaratively",
                "Stream supports map filter and reduce operations",
                "Parallel stream executes operations concurrently",
                "Optional avoids null pointer exceptions",
                "Method reference refers to existing method",
                "Default methods are allowed in interfaces",
                "Static methods are allowed in interfaces",
                "Java supports module system from Java 9",
                "JDBC connects Java applications to databases",
                "PreparedStatement prevents SQL injection",
                "Connection represents database session",
                "ResultSet holds query result data",
                "Spring framework simplifies enterprise Java development",
                "Dependency injection reduces tight coupling",
                "Inversion of control delegates object creation",
                "Spring Boot simplifies Spring configuration",
                "REST API uses HTTP methods for communication",
                "GET retrieves data from server",
                "POST creates new resource",
                "PUT updates existing resource",
                "DELETE removes a resource",
                "JSON is common data exchange format",
                "Jackson library serializes Java objects to JSON",
                "Microservices architecture splits application into services",
                "API Gateway routes requests to services",
                "Service discovery locates microservice instances",
                "Circuit breaker prevents cascading failures",
                "Config server centralizes configuration",
                "JWT is used for stateless authentication",
                "OAuth2 is authorization framework",
                "Spring Security handles authentication and authorization",
                "MongoDB is a NoSQL document database",
                "Collection in MongoDB stores documents",
                "Index improves query performance",
                "Aggregation performs complex data processing",
                "Kafka is a distributed event streaming platform",
                "Producer publishes messages to Kafka topics",
                "Consumer reads messages from Kafka topics",
                "Partition enables parallel processing",
                "Offset tracks message consumption",
                "Event driven architecture reacts to events",
                "CQRS separates read and write models",
                "Event sourcing stores state as events",
                "SAGA manages distributed transactions",
                "Cache improves application performance",
                "Redis is in memory data store",
                "Cache aside pattern loads data on demand",
                "Read through cache loads data automatically",
                "Write through cache writes to cache and database",
                "Kubernetes orchestrates containerized applications",
                "Pod is smallest deployable unit in Kubernetes",
                "Service exposes pods internally or externally",
                "Ingress manages external access",
                "Docker packages applications into containers",
                "CI CD automates build and deployment",
                "Unit testing validates individual components",
                "JUnit is popular Java testing framework",
                "Mockito mocks dependencies in tests",
                "Integration testing validates component interaction",
                "Design patterns provide reusable solutions",
                "Singleton ensures single instance of class",
                "Factory creates objects without exposing logic",
                "Builder constructs complex objects step by step",
                "Strategy defines interchangeable algorithms",
                "Observer notifies dependent objects",
                "Decorator adds behavior dynamically",
                "Adapter converts one interface to another",
                "Facade simplifies complex subsystem",
                "Proxy controls access to object",
                "SOLID principles improve code quality",
                "Single responsibility enforces one reason to change",
                "Open closed principle supports extension not modification",
                "Liskov substitution ensures subtype compatibility",
                "Interface segregation avoids fat interfaces",
                "Dependency inversion depends on abstractions",
                "Clean code improves readability and maintainability",
                "Logging helps in debugging and monitoring",
                "SLF4J provides logging abstraction",
                "Logback is logging implementation",
                "Metrics provide system performance insights",
                "Tracing helps track request flow",
                "Observability improves system reliability"
        );
    }
}
